### ISSUE TITLE
Sending data to API through post request

### ISSUE THREAD

**Issue by Javierko** [byCedric/office-marathon#3]
### Description of the feature
As I see in the code
https://github.com/byCedric/office-marathon/blob/2ddfbb571e78b02957b8d2f3a04f473d23c83048/src/services/location/track.ts#L64
at this moment the data are currently saving to phone storage, but what about sending to API with post request?
It is even possible to do it this way or need to do something different?

### Motivation
I think it's a cool idea and it would help a lot of people.

### Additional context
It's very usefull when you need to show up data from mobile device to for example in web application.

**Comment by byCedric** [comment]
Haha, thanks, I just required an example for background location usage. But, integrating an API is possible and not that hard.

Right now, I used a `location -> task -> write to storage` flow to display the data whenever we need it. You can add API communication within the [`src/service/location/track.ts`](https://github.com/byCedric/office-marathon/blob/main/src/services/location/track.ts#L53-L69)'s task. Or even schedule a background fetch task if you want to.

Feel free to fork it and do that :)
